version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command:
            python -m unittest test
