version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command:
            python -m unittest test

  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: create .pypirc
          command: |
            echo "[pypi]" > $HOME/.pypirc
            echo "username =" $PYPIUSER >> $HOME/.pypirc
            echo "password =" $PYPIPASS >> $HOME/.pypirc
      - run:
          name: packaging
          command:
            python setup.py sdist
      - run:
          name: install twine
          command:
            sudo pip install twine
      - run:
          name: upload
          command:
            twine upload dist/*

workflows:
    version: 2
    build:
      jobs:
        - build
        - deploy:
            filters:
              branches:
                only: release

